<a href="https://colab.research.google.com/github/Sakshamsinha23/Machine-Learning/blob/main/Cleaning_Numerical_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pyforest
import pyforest

Collecting pyforest
  Downloading pyforest-1.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyforest
  Building wheel for pyforest (setup.py) ... done
  Created wheel for pyforest: filename=pyforest-1.1.2-py2.py3-none-any.whl size=15900 sha256=f5d400fc232cebf0f27af07872946b22b6be9d56470789a4d157be9e4d97e760
  Stored in directory: /root/.cache/pip/wheels/c5/ca/73/5cdc3d087111bfbdef90be5457aa03c00c0e32241b2752445c
Successfully built pyforest
Installing collected packages: pyforest
Successfully installed pyforest-1.1.2

In [3]:
data=pd.read_csv('/content/loan.csv')
data.head(10)

    Loan_ID Gender Married Dependents  ... Loan_Amount_Term Credit_History  Property_Area  Loan_Status
0  LP001002   Male      No          0  ...            360.0            1.0          Urban            Y
1  LP001003   Male     Yes          1  ...            360.0            1.0          Rural            N
2  LP001005   Male     Yes          0  ...            360.0            1.0          Urban            Y
3  LP001006   Male     Yes          0  ...            360.0            1.0          Urban            Y
4  LP001008   Male      No          0  ...            360.0            1.0          Urban            Y
5  LP001011   Male     Yes          2  ...            360.0            1.0          Urban            Y
6  LP001013   Male     Yes          0  ...            360.0            1.0          Urban            Y
7  LP001014   Male     Yes         3+  ...            360.0            0.0      Semiurban            N
8  LP001018   Male     Yes          2  ...            360.0            1.0          Urban            Y
9  LP001020   Male     Yes          1  ...            360.0            1.0      Semiurban            N

[10 rows x 13 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [9]:
data.select_dtypes(include='float64').columns

Index(['CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term',
       'Credit_History'],
      dtype='object')

In [17]:
from sklearn.impute import SimpleImputer

si=SimpleImputer(strategy="mean")
arr = si.fit_transform(data[['CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term',
       'Credit_History']])

In [23]:
new_data= pd.DataFrame(arr,columns=data.select_dtypes(include='float64').columns)
new_data

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History
0                  0.0  146.412162             360.0             1.0
1               1508.0  128.000000             360.0             1.0
2                  0.0   66.000000             360.0             1.0
3               2358.0  120.000000             360.0             1.0
4                  0.0  141.000000             360.0             1.0
..                 ...         ...               ...             ...
609                0.0   71.000000             360.0             1.0
610                0.0   40.000000             180.0             1.0
611              240.0  253.000000             360.0             1.0
612                0.0  187.000000             360.0             1.0
613                0.0  133.000000             360.0             0.0

[614 rows x 4 columns]

In [22]:
new_data.isnull().sum()

CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
dtype: int64

In [24]:
data["LoanAmount"].mean()

146.41216216216216