<a href="https://colab.research.google.com/github/Sakshamsinha23/Machine-Learning/blob/main/One_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pyforest
import pyforest

Requirement already satisfied: pyforest in /usr/local/lib/python3.10/dist-packages (1.1.2)

In [2]:
data=pd.read_csv('/content/loan.csv')
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [3]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [4]:
data["Gender"].mode

<bound method Series.mode of 0        Male
1        Male
2        Male
3        Male
4        Male
        ...
609    Female
610      Male
611      Male
612      Male
613    Female
Name: Gender, Length: 614, dtype: object>

In [5]:
data["Gender"].fillna(data["Gender"].mode,inplace=True)

In [6]:
data.isnull().sum()

Loan_ID               0
Gender                0
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [7]:
data["Married"].fillna(data["Married"].mode,inplace=True)
data.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [38]:
# get dummies
# Convert 'Gender' and 'Married' columns to strings if needed
en_data = data[["Gender", "Married"]].astype(str)
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 6 columns):
 #   Column                                                                                                                                                                                                                                   Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                   --------------  -----
 0   Gender_<bound method Series.mode of 0        Male
1        Male
2        Male
3        Male
4        Male
        ...
609    Female
610      Male
611      Male
612      Male
613    Female
Name: Gender, Length: 614, dtype: object>  614 non-null    bool
 1   Gender_Female                                                                                                                                                                                                                            614 non-null    bool
 2   Gender_Male                                                                                                                                                                                                                              614 non-null    bool
 3   Married_<bound method Series.mode of 0       No
1      Yes
2      Yes
3      Yes
4       No
      ...
609     No
610    Yes
611    Yes
612    Yes
613     No
Name: Married, Length: 614, dtype: object>                                 614 non-null    bool
 4   Married_No                                                                                                                                                                                                                               614 non-null    bool
 5   Married_Yes                                                                                                                                                                                                                              614 non-null    bool
dtypes: bool(6)
memory usage: 3.7 KB

**Scikit-learn library**

In [74]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Initialize the OneHotEncoder with drop='first'
ohe = OneHotEncoder( sparse_output=False)

# Fit and transform the data
arr = ohe.fit_transform(en_data)

# Get the correct column names
columns = ohe.get_feature_names_out(en_data.columns)

# Print the array and column names
print(arr)
print(columns)

# Create the DataFrame with the correct column names
encoded_df = pd.DataFrame(arr, columns=columns)

# View the result
print(encoded_df)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]]
['Gender_Female' 'Gender_Male' 'Married_No' 'Married_Yes']
   Gender_Female  Gender_Male  Married_No  Married_Yes
0            0.0          1.0         0.0          1.0
1            1.0          0.0         1.0          0.0
2            1.0          0.0         0.0          1.0
3            0.0          1.0         1.0          0.0
4            1.0          0.0         0.0          1.0

In [65]:
arr

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.]])

In [66]:
encoded_df

   Gender_Female  Gender_Male  Married_No  Married_Yes
0            0.0          1.0         0.0          1.0
1            1.0          0.0         1.0          0.0
2            1.0          0.0         0.0          1.0
3            0.0          1.0         1.0          0.0
4            1.0          0.0         0.0          1.0

**Using Drop First Function**

In [76]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(sparse_output=False,drop='first')

# fit and transform
arr = ohe.fit_transform(en_data)

columns=ohe.get_feature_names_out(en_data.columns)

encoded_df=pd.DataFrame(arr,columns=columns)

In [77]:
arr

array([[1., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [78]:
encoded_df

   Gender_Male  Married_Yes
0          1.0          1.0
1          0.0          0.0
2          0.0          1.0
3          1.0          0.0
4          0.0          1.0